### ISSUE TITLE
Make a custom Logger wrapper

### ISSUE THREAD

**Issue by kinggoesgaming** [MinigameCore/MinigameCore#30]
Since we will have a lot of logging to handle, a wrapper that handles whether to log something or not(depending on currently active logging level in config).. suffix etc

**Comment by Flibio** [comment]
This sounds good, it would extend the slf4j `Logger` that Sponge uses?

**Comment by kinggoesgaming** [comment]
it will just wrap around it... yes..

**Comment by Flibio** [comment]
Sounds good to me.

**Comment by kinggoesgaming** [comment]
This is under way, however, because config file is not available, currently it will not check if a message has to be logged or not

**Comment by kinggoesgaming** [comment]
MCLogger is now an instance of `org.slf4j.Logger`

The PR should be in tomorrow
